site_name: Computacional Thinking
site_author: Arnaldo Viana 


extra:  
    materia: Computacional Thinking with Python
    professor: Arnaldo Viana
    ano: 2023

theme:
  feature:
    tabs: true
  name: active-handout
#  custom_dir: overrides

docs_dir: material
site_dir: docs

repo_url: https://github.com/arnaldojr/computacionalthinking/
repo_name: "Computacional Thinking with Python"
site_url: https://arnaldojr.github.io/computacionalthinking/


# Extensions / plugins

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js

extra:
  ihandout_config:
#    counter:
#      - question
#      - tip
#      - exercise
#      - example
    report:
      api-base: https://devlife.insper-comp.com.br/api/offerings/1/
      url: https://devlife.insper-comp.com.br/api/offerings/1/exercises/

use_directory_urls: false

# Extensions / plugins
plugins:
  - git-revision-date-localized
  - search
  - termynal
  - mkdocs-jupyter:

      include_source: True
      execute: False

extra_css:
  - css/termynal.css
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-css@main/devlife.css


markdown_extensions:
  - markdown.extensions.tables
  # - markdown.extensions.extra  
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: code
      check_paths: true


nav:
  - Home: index.md
  - Playground: aulas/ctp/intro/playground.md
  - Sobre o curso: sobre/sobre.md
  - Agenda: agenda/agenda.md
  - CheckPoint: 
    - sobre: aulas/checkpoint/index.md
    - CP5: aulas/checkpoint/cp5.md
  - Pensamento computacional: aulas/ctp/intro/intro-ctp.md
  - Fundamentos de Python:
    - Introdução ao Python: aulas/ctp/python/intro-python.md
    - Tipos de Dados e Variáveis: aulas/ctp/python/data-types.md
    - Controle de Fluxo:
      - Estruturas de decisão:
        - if-elif-else: aulas/ctp/python/decision-structures.md
      - Estruturas de Repetição:    
        - while loop : aulas/ctp/python/repetition-structures-while-loop.md
        - for Loop: aulas/ctp/python/repetition-structures-for-loop.md
    - Estruturas de Dados:
      - Listas e Tuplas: aulas/ctp/python/lists-tuples.md
      - Dicionários e Conjuntos: aulas/ctp/python/dict-sets.md
    - Funções e Módulos:
      - Funções: aulas/ctp/python/functions-modules.md
      - Módulos e Pacotes: aulas/ctp/python/modules.md
      - Módulos externos: aulas/ctp/python/modules2.md
    - Manipulação de Dados e Arquivos:    
      - Manipulação de arquivos: aulas/ctp/python/files-maniputation.md
    - Programação Orientada a Objetos:
      - Classes e Objetos: aulas/ctp/python/oop-classes-objects.md
      - Herança, Encapsulamento e Métodos Privados: aulas/ctp/python/oop-inheritance.md
      - Polimorfismo: aulas/ctp/python/oop-polymorphism.md
    - Erros e Exceções:
      - Tratamento de Erros - Try, Except: aulas/ctp/python/errors-exceptions.md
  - Algoritmos e Estruturas de Dados:
    - Busca: 
      - O problema da busca: aulas/ctp/algorithms/problem-search.md
      - Busca Sequencial: aulas/ctp/algorithms/sequential-search.md
      - Busca Binária: aulas/ctp/algorithms/binary-search.md
    - Ordenação:
      - O caso da Ordenação: aulas/ctp/algorithms/sorting-algorithms.md
      - Bubble Sort: aulas/ctp/algorithms/bubble-sort.md
      - Selection Sort: aulas/ctp/algorithms/selection-sort.md
      - Insertion Sort: aulas/ctp/algorithms/insertion-sort.md
      - Merge Sort: aulas/ctp/algorithms/merge-sort.md
      - Quick Sort: aulas/ctp/algorithms/quick-sort.md
    - Recursão:
      - Recursividade: aulas/ctp/algorithms/recursion.md
    - Análise de Algoritmos:
      - Notação Big O: aulas/ctp/algorithms/big-o-notation.md  
  - Configuração do Ambiente de Desenvolvimento:
    - Criação de um Ambiente Virtual: aulas/ctp/environment-setup/virtual-environment.md
  - Desenvolvimento Web com Python:
    - Introdução ao Desenvolvimento Web: aulas/ctp/web/intro-web-development.md
    - Técnicas Básicas de Raspagem de Dados:
      - Introdução ao Web Scraping: aulas/ctp/web/webscraping/intro-webscraping.md
      - WWW com Requests e consumo de API: aulas/ctp/web/webscraping/data-scraping-requests.md
    - Web Scraping:
      - BeautifulSoup: aulas/ctp/web/webscraping/web_scraping.ipynb
    # - Flask:
    #   - Introdução ao Flask: aulas/ctp/web/flask/intro-flask.md
    #   - Rotas e Requisições GET: aulas/ctp/web/flask/routes-get-requests.md
    #   - Formulários e Requisições POST: aulas/ctp/web/flask/forms-post-requests.md
    #   - Renderização de Templates: aulas/ctp/web/flask/template-rendering.md
    #   - Conexão com Banco de Dados: aulas/ctp/web/flask/database-connection.md
    # - ORM (Object-Relational Mapping): aulas/ctp/web/orm.md
    # - Segurança em Aplicações Web: aulas/ctp/web/security.md
    # - Deploy de Aplicações: aulas/ctp/web/deploy.md
    - Banco de dados:
      - BD com Python: aulas/ctp/bd/index.md
  - Laboratórios:
    - Solução Labs:
      - Lab02 - Tipos de dados e Variáveis: aulas/ctp/labs/solutions/solution-data-types.ipynb 
      - Lab03 - Estrutura de Decisão: aulas/ctp/labs/solutions/solution-decision-structures.ipynb 
      - Lab04 - Erros comuns: aulas/ctp/labs/solutions/solution-common-errors.ipynb 
      - Lab05 - Loops for e while, listas e tuplas: aulas/ctp/labs/solutions/solution-loop-structures-data-nivel1.ipynb
      - Lab06 - Dicionários e conjuntos: aulas/ctp/labs/solutions/solution-dict.ipynb
      - Lab07 - Problema da busca: aulas/ctp/labs/solutions/solution-search.ipynb
    - Lab01 - Comece aqui!: aulas/ctp/intro/infra.md
    - Lab02 - Tipos de dados e Variáveis: aulas/ctp/labs/lab-data-types.md
    - Lab03 - Estrutura de Decisão: aulas/ctp/labs/lab-decision-structures.md
    - Lab04 - Erros comuns: aulas/ctp/labs/common-errors.ipynb
    - Lab05 - Loops for e while, listas e tuplas: aulas/ctp/labs/lab-loops-data-structures.md
    - Lab06 - Dicionários, conjuntos e afins...: aulas/ctp/labs/lab-loops-dict-sets.md
    - Lab07 - Problema da busca: aulas/ctp/labs/lab-search.md
    - Lab08 - Ordenação: aulas/ctp/labs/lab-sorting.md
  - Projetos Práticos:
    - Jogo da Adivinhação: aulas/ctp/projects/guessing-game.md
    - Agenda simples: aulas/ctp/projects/agenda.md
    - Projetos Temáticos: 
      - Eventos - Proj1: aulas/ctp/projects/proj1-eventos.md
      - Finanças - Proj2: aulas/ctp/projects/proj2-financas.md
      - Jokenpô - Proj3: aulas/ctp/projects/proj3-pedra-papel-tesoura.md
      - Jogo da Velha - Proj4: aulas/ctp/projects/proj4-jogo-da-velha.md
  - Recursos Adicionais:
    - Referências e Leituras Complementares: aulas/ctp/resources/references.md


# nav:
#     - Operadores:
#       - Aritméticos: aulas/ctp/python/operators/arithmetic.md
#       - Relacionais: aulas/ctp/python/operators/relational.md
#       - Lógicos: aulas/ctp/python/operators/logical.md
#     - Funções e Módulos:
#       - Definindo Funções: aulas/ctp/python/functions-modules/defining-functions.md
#       - Parâmetros e Argumentos: aulas/ctp/python/functions-modules/parameters-arguments.md
#       - Funções Lambda: aulas/ctp/python/functions-modules/lambda-functions.md
#       - Importando Módulos: aulas/ctp/python/functions-modules/importing-modules.md
#     - Erros e Exceções:
#       - Tratamento de Erros: aulas/ctp/python/errors-exceptions/error-handling.md
#       - Try, Except, Finally: aulas/ctp/python/errors-exceptions/try-except-finally.md
#   - Estruturas de Dados:
#     - Listas e Tuplas: aulas/ctp/data-structures/lists-tuples.md
#     - Dicionários: aulas/ctp/data-structures/dicts-sets.md
    # - Recursividade: aulas/ctp/python/recursion.md
    # - Algoritmos de Ordenação: aulas/ctp/python/sorting-algorithms.md
    # - Algoritmos de Busca: aulas/ctp/python/search-algorithms.md
    # - Algoritmos de Grafos: aulas/ctp/python/graph-algorithms.md

  # - Desenvolvimento Web com Python:
  #   - Introdução ao Desenvolvimento Web: aulas/ctp/web/intro-web-development.md
  #   - Web scraping: aulas/ctp/web/web-scraping.md

    # - Flask:
    #   - Introdução ao Flask: aulas/ctp/web/flask/intro-flask.md
    #   - Rotas e Visualizações: aulas/ctp/web/flask/routes-views.md
    #   - Templates: aulas/ctp/web/flask/templates.md
    #   - Formulários e Requisições: aulas/ctp/web/flask/forms-requests.md
    #   - Integração com Banco de Dados: aulas/ctp/web/flask/database-integration.md
    # # - Django:
    # #   - Introdução ao Django: aulas/ctp/web/django/intro-django.md
    # #   - Estrutura de Projeto: aulas/ctp/web/django/project-structure.md
    # #   - Modelos e Banco de Dados: aulas/ctp/web/django/models-database.md
    # #   - Autenticação e Autorização: aulas/ctp/web/django/auth.md
    # - Segurança em Aplicações Web: aulas/ctp/web/security.md
    # - Deploy de Aplicações: aulas/ctp/web/deploy.md
