site_name: Computacional Thinking
site_author: Arnaldo Viana 


extra:  
    materia: Computacional Thinking with Python
    professor: Arnaldo Viana
    ano: 2023

theme:
  feature:
    tabs: true
  name: active-handout
#  custom_dir: overrides

docs_dir: material
site_dir: docs

repo_url: https://github.com/arnaldojr/computacionalthinking/
repo_name: "Computacional Thinking with Python"
site_url: https://arnaldojr.github.io/computacionalthinking/


# Extensions / plugins

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js

extra:
  ihandout_config:
#    counter:
#      - question
#      - tip
#      - exercise
#      - example
    report:
      api-base: https://devlife.insper-comp.com.br/api/offerings/1/
      url: https://devlife.insper-comp.com.br/api/offerings/1/exercises/

use_directory_urls: false

# Extensions / plugins
plugins:
  - git-revision-date-localized
  - search
  - termynal
  - mkdocs-jupyter:

      include_source: True
      execute: False

extra_css:
  - css/termynal.css
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-css@main/devlife.css


markdown_extensions:
  - markdown.extensions.tables
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: code
      check_paths: true


nav:
  - Home: index.md
  - Sobre o curso: sobre/sobre.md
  - Agenda: agenda/agenda.md
  - CheckPoint: aulas/checkpoint/index.md
  - Pensamento computacional: aulas/ctp/intro/intro-ctp.md
  - Fundamentos de Python:
    - Introdução ao Python: aulas/ctp/python/intro-python.md
    - Tipos de Dados e Variáveis: aulas/ctp/python/data-types.md
    - Estruturas de Controle: aulas/ctp/python/control-structures.md
    - Funções e Módulos: aulas/ctp/python/functions-modules.md
  # - Estruturas de Dados:
  #   - Listas e Tuplas: aulas/ctp/data-structures/lists-tuples.md
  #   - Dicionários e Conjuntos: aulas/ctp/data-structures/dicts-sets.md
  # - Pensamento Algorítmico:
  #   - Algoritmos Básicos: aulas/ctp/algorithms/basic-algorithms.md
  #   - Estratégias de Solução de Problemas: aulas/ctp/algorithms/problem-solving.md

  - Laboratórios:
    - Lab01 - Comece aqui!: aulas/ctp/intro/infra.md
    - Lab02 - Exercícios com Tipos de dados e Variáveis: aulas/ctp/labs/lab-data-types.md
  #   - Lab03 - Manipulando Estruturas de Dados: aulas/ctp/labs/lab-data-structures.md
  #   - Lab04 - Desenvolvendo Algoritmos: aulas/ctp/labs/lab-algorithms.md
  # - Projetos Práticos:
  #   - Projeto 01 - Jogo da Adivinhação: aulas/ctp/projects/guessing-game.md
  #   - Projeto 02 - Gerenciador de Tarefas: aulas/ctp/projects/task-manager.md
  - Recursos Adicionais:
    - Referências e Leituras Complementares: aulas/ctp/resources/references.md


# nav:
#   - Home: index.md
#   - Sobre o curso: sobre/sobre.md
#   - Agenda: agenda/agenda.md
#   - Pensamento computacional: aulas/ctp/intro/intro-ctp.md
#   - Fundamentos de Python:
#     - Introdução ao Python: aulas/ctp/python/intro-python.md #História e Filosofia, Primeiros Passos
#     - Tipos de Dados e Variáveis: aulas/ctp/python/data-types.md #tipo primitivos como Números, Strings, Booleanos. Variáveis e Atribuição. Conversão de Tipos. entrada e saida
#     - Operadores:
#       - Aritméticos: aulas/ctp/python/operators/arithmetic.md
#       - Relacionais: aulas/ctp/python/operators/relational.md
#       - Lógicos: aulas/ctp/python/operators/logical.md
#     - Controle de Fluxo:
#       - Estruturas de Decisão: aulas/ctp/python/flow-control/decision-structures.md
#       - Estruturas de Seleção: aulas/ctp/python/flow-control/select-structures.md
#       - Estruturas de Repetição:
#         - For Loop: aulas/ctp/python/repetition-structures/for-loop.md
#         - While Loop: aulas/ctp/python/repetition-structures/while-loop.md
#         - Break e Continue: aulas/ctp/python/repetition-structures/break-continue.md
#     - Funções e Módulos:
#       - Definindo Funções: aulas/ctp/python/functions-modules/defining-functions.md
#       - Parâmetros e Argumentos: aulas/ctp/python/functions-modules/parameters-arguments.md
#       - Funções Lambda: aulas/ctp/python/functions-modules/lambda-functions.md
#       - Importando Módulos: aulas/ctp/python/functions-modules/importing-modules.md
#     - Erros e Exceções:
#       - Tratamento de Erros: aulas/ctp/python/errors-exceptions/error-handling.md
#       - Try, Except, Finally: aulas/ctp/python/errors-exceptions/try-except-finally.md
#   - Estruturas de Dados:
#     - Listas e Tuplas: aulas/ctp/data-structures/lists-tuples.md
#     - Dicionários: aulas/ctp/data-structures/dicts-sets.md
#   - Laboratórios:
#     - Lab01 - Comece aqui!: aulas/ctp/intro/infra.md
#     - Lab02 - Exercícios com Estruturas de Decisão: aulas/ctp/labs/lab-decision-structures.md
#     - Lab03 - Exercícios com Estruturas de Seleção: aulas/ctp/labs/lab-select-structures.md
#     - Lab04 - Exercícios com Estruturas de Repetição: aulas/ctp/labs/lab-repetition-structures.md
#     - Lab05 - Manipulando Estruturas de Dados: aulas/ctp/labs/lab-data-structures.md
#     - Lab06 - Desenvolvendo Algoritmos: aulas/ctp/labs/lab-algorithms.md
#   - Recursos Adicionais:
#     - Referências e Leituras Complementares: aulas/ctp/resources/references.md

